# Generated by Django 2.2.4 on 2022-01-30 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_team_submit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('leaderboard_freeze', models.BooleanField(default=0)),
                ('killcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='final_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Killcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team')),
            ],
        ),
    ]
