# Generated by Django 2.2.4 on 2022-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20220131_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='round',
        ),
        migrations.AddField(
            model_name='answer',
            name='round_no',
            field=models.IntegerField(default=1),
        ),
    ]
