# Generated by Django 2.2.4 on 2022-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20220131_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='text',
            new_name='killer_note',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='image',
        ),
        migrations.AddField(
            model_name='evidence',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='encrypt_img',
            field=models.ImageField(blank=True, null=True, upload_to='encryptImage/'),
        ),
        migrations.AddField(
            model_name='round',
            name='evidence_img',
            field=models.ImageField(blank=True, null=True, upload_to='evidenceImage/'),
        ),
        migrations.AlterField(
            model_name='round',
            name='tries',
            field=models.IntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
