# Generated by Django 2.2.4 on 2022-01-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='participant4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='participant4_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='participant5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='participant5_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant1_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant2_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='participant3_email',
            field=models.EmailField(max_length=254),
        ),
    ]
