# Generated by Django 2.2.4 on 2022-01-29 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220127_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('data', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, upload_to='profilepics/')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(default=1)),
                ('riddle', models.TextField()),
                ('killer_msg', models.TextField()),
                ('ca', models.TextField(default=None)),
                ('ca_location', models.CharField(max_length=400)),
                ('ca_victim', models.CharField(max_length=400)),
                ('tries', models.IntegerField(default=3)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='guessed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None)),
                ('image', models.ImageField(blank=True, default=None, upload_to='evidenceImage/')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Round')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=400)),
                ('victim', models.CharField(max_length=400)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('tries', models.IntegerField(default=1)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Round')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team')),
            ],
        ),
    ]
