# Generated by Django 2.2.4 on 2022-01-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_team_roundno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='participant5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='participant5_email',
        ),
    ]
