# Generated by Django 2.2.4 on 2022-01-31 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20220130_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Team'),
        ),
    ]
