# Generated by Django 2.2.4 on 2023-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20220201_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='universal',
            name='ans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
