# Generated by Django 2.2.4 on 2023-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_universal_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_id', models.CharField(max_length=30, verbose_name='Unique ID of the clue')),
                ('content', models.TextField(max_length=3000, verbose_name='Content of the clue')),
            ],
        ),
    ]
