# Generated by Django 2.2.4 on 2023-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_clueredirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='location',
            field=models.CharField(default='location1', max_length=300, verbose_name='Location of the field'),
            preserve_default=False,
        ),
    ]
