# Generated by Django 2.2.4 on 2023-03-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_clue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clueredirect',
            name='redirect_to',
            field=models.CharField(max_length=300, verbose_name='Redirect URI for the clue'),
        ),
    ]
