# Generated by Django 2.2.4 on 2023-04-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20230401_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClueAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300, verbose_name='Team name')),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Clue')),
            ],
        ),
    ]
